HelpDesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('desk.urls'))
]

desk/urls.py
from django.urls import path, include
from rest_framework import routers

from desk.API.resorces import LoginGetToken, ListDetailHelpStatement, RegistrationAPI, LogoutAPI, \
    CreateUpdateHelpStatement, CreateCommentAPIView, ListReturnHelpStatementAPIView, SuccessHelpStatementAPIView, \
    RejectedReturnHelpStatement
from desk.views import SelfLogin, SelfRegistration, SelfLogout, ListHelpStatement, DetailHelpStatement, CreateComment, \
    CreateHelpStatement, UpdateHelpStatement, ReturnedHelpStatement, DeleteReturnHelpStatement, \
    ListReturnHelpStatement, UpdateSuccessHelpStatement


router = routers.SimpleRouter()
router.register(r'list', ListDetailHelpStatement)
router.register(r'create', CreateUpdateHelpStatement)
router.register(r'comment', CreateCommentAPIView)
router.register(r'admin/list', ListReturnHelpStatementAPIView)
router.register(r'success', SuccessHelpStatementAPIView)
router.register(r'rejected/return', RejectedReturnHelpStatement)


urlpatterns = [
    path('login/', SelfLogin.as_view(), name='login'),
    path('registration/', SelfRegistration.as_view(), name='registration'),
    path('logout/', SelfLogout.as_view(), name='logout'),

    path('list/', ListHelpStatement.as_view(), name='list'),
    path('create/statement/', CreateHelpStatement.as_view(), name='create_statement'),
    path('update/statement/<int:pk>', UpdateHelpStatement.as_view(), name='update_statement'),
    path('returned/statement/<int:pk>', ReturnedHelpStatement.as_view(), name='return_statement'),
    path('detail/<int:pk>/', DetailHelpStatement.as_view(), name='detail'),
    path('create/comment/<int:pk>/', CreateComment.as_view(), name='create_comment'),

    path('success/<int:pk>', UpdateSuccessHelpStatement.as_view(), name='success_statement'),
    path('list/returned/', ListReturnHelpStatement.as_view(), name='list_returned'),
    path('delete/statement/<int:pk>', DeleteReturnHelpStatement.as_view(), name='delete_statement'),

    # API

    path('api/login/', LoginGetToken.as_view(), name='api_login'),
    path('api/registration/', RegistrationAPI.as_view(), name='api_registration'),
    path('api/logout/', LogoutAPI.as_view(), name='api_logout'),
    path('api/', include(router.urls)),
]

desk/models.py
from datetime import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.timezone import make_aware
from rest_framework.authtoken.models import Token

CHOICE_LEVEL = [
    ('L', 'Low'),
    ('M', 'Medium'),
    ('H', 'High')
]
CHOICE_SUCCESS = [
    ('P', 'Process'),
    ('C', 'Confirmed'),
    ('F', 'Rejected'),
    ('R', 'Returned')
]


class MyUser(AbstractUser):
    pass


class Statement(models.Model):
    user = models.ForeignKey(MyUser, related_name='master_statement', on_delete=models.CASCADE)
    title = models.CharField(max_length=150, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    level_important = models.CharField(choices=CHOICE_LEVEL, blank=False, null=False, default='L', max_length=10)
    success = models.CharField(choices=CHOICE_SUCCESS, blank=False, null=False, default='P', max_length=10)
    create_at = models.DateTimeField()

    class Meta:
        ordering = ['-create_at', 'title']
        unique_together = ['user', 'title']

    def save(self, *args, **kwargs):
        if not self.id:
            self.create_at = make_aware(datetime.now())
        return super().save(*args, **kwargs)


class Comment(models.Model):
    user = models.ForeignKey(MyUser, related_name='master_comment', on_delete=models.CASCADE)
    statement = models.ForeignKey(Statement, related_name='state_comment', on_delete=models.CASCADE)
    text = models.TextField(blank=False, null=False)
    create_at = models.DateTimeField()

    class Meta:
        ordering = ['create_at']

    def save(self, *args, **kwargs):
        if not self.id:
            self.create_at = make_aware(datetime.now())
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.text


class MyToken(Token):
    last_action = models.DateTimeField(null=True)

templates/admin_error_success.html
{% extends 'base.html' %}


{% block title %}
    <title>ERROR SUCCESS</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'list' %}">List statement</a></span>
    <br><hr><br>

    <form method="post" action="{% url 'success_statement' statement.id %}">
        {% csrf_token %}
        <input type="hidden" value="confirmed" name="success">
        <input type="submit" value="Подтвердить">
    </form>
    <form method="post" action="{% url 'success_statement' statement.id %}">
        {% csrf_token %}
        <input type="text" name="comment">
        <input type="hidden" value="rejected" name="success">
        <input type="submit" value="Отклонить">
    </form>

    <h3 style="color: red">Don't enter comment!</h3>
{% endblock %}

templates/admin_return_statement.html
{% extends 'base.html' %}
{% load mytags %}


{% block title %}
    <title>Returned Statement</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'logout' %}">Logout</a></span><br>
    <span><a href="{% url 'list' %}">List</a></span><br>
    <br><hr><br>

    {% for statement in object_list %}
        <h3>{{ statement.title }}</h3>
        <p>{{ statement.description }}</p>
        <i><b>Impotant: {{ statement.get_level_important_display }}</b></i>
        <i>Status: {{ statement.get_success_display }}</i><br>
        <pre><i>{{ statement.create_at|date:'Y/m/d - h:i:s' }}</i></pre>
        <hr>
        <p><i>Last comment: </i>{{ statement.state_comment|filter_first:statement.id }}</p>
        <hr>
        <form method="get" action="{% url 'detail' statement.id %}">
            <input type="submit" value="Detail">
        </form>
        {% if request.user.is_staff %}
            <form method="post" action="{% url 'success_statement' statement.id %}">
                {% csrf_token %}
                <input type="hidden" value="confirmed" name="success">
                <input type="submit" value="Подтвердить">
            </form>
            <form method="post" action="{% url 'delete_statement' statement.id %}">
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
        {% endif %}
        <hr>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/login.html
{% extends 'base.html' %}


{% block title %}
    <title>Login</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'registration' %}">Registration</a></span><br>
    <br><hr><br>

    <form method="post">
        {{ form }}
        {% csrf_token %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}


{% block title %}
    <title>Registration</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'login' %}">Login</a></span><br>
    <br><hr><br>

    <form method="post">
        {{ form }}
        {% csrf_token %}
        <input type="submit" value="Registration">
    </form>
{% endblock %}

templates/user_create_statement.html
{% extends 'base.html' %}


{% block title %}
    <title>Create statement</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'logout' %}">Logout</a></span><br>
    <span><a href="{% url 'list' %}">List statement</a></span><br>
    <br><hr><br>

    <form method="post">
        {{ form.as_ul }}
        {% csrf_token %}
        <input type="submit" value="Create">
    </form>
{% endblock %}

templates/user_detail_statement.html
{% extends 'base.html' %}


{% block title %}
    <title>Detail statement</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'logout' %}">Logout</a></span><br>
    <span><a href="{% url 'list' %}">List statement</a></span><br>
    {% if request.user.is_staff %}
        <span><a href="{% url 'list_returned' %}">List Returned</a></span><br>
    {% endif %}
    <br><hr><br>

    <h3>{{ object.title }}</h3>
    <p>{{ object.description }}</p>
    <i><b>Impotant: {{ object.get_level_important_display }}</b></i>
    <i>Status: {{ object.get_success_display }}</i><br>
    <pre><i>{{ object.create_at|date:'Y/m/d - h:i:s' }}</i></pre>
    <hr>
    {% for comment in object.state_comment.all %}
        <p>{{ comment.text }}</p>
        <i>{{ comment.create_at }}</i>
    {% endfor %}
    <hr>
    {% if object.success != 'R' and object.success != 'Returned' %}
        <form method="post" action="{% url 'create_comment' statement.id %}">
        <input type="text" name="text">
        {% csrf_token %}
        <input type="submit" value="Отправить">
    </form>
    {% endif %}
    <hr>
{% endblock %}

templates/user_list_statement.html
{% extends 'base.html' %}
{% load mytags %}


{% block title %}
    <title>List Statements</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'logout' %}">Logout</a></span><br>
    <span><a href="{% url 'create_statement' %}">Create statement</a></span><br>
    {% if request.user.is_staff %}
        <span><a href="{% url 'list_returned' %}">List Returned</a></span><br>
    {% endif %}
    <br><hr><br>

    {% for statement in object_list %}
        {% if statement.success != 'R' %}
            <h3>{{ statement.title }}</h3>
            <p>{{ statement.description }}</p>
            <i><b>Impotant: {{ statement.get_level_important_display }}</b></i>
            <i>Status: {{ statement.get_success_display }}</i><br>
            <pre><i>{{ statement.create_at|date:'Y/m/d - h:i:s' }}</i></pre>
            <hr>
            <p><i>Last comment: </i>{{ statement.state_comment|filter_first:statement.id }}</p>
            <hr>
            <form method="get" action="{% url 'detail' statement.id %}">
                <input type="submit" value="Detail">
            </form>
            {% if request.user.is_staff %}
                {% if statement.success == 'P' or statement.success == 'R' %}
                    <form method="post" action="{% url 'success_statement' statement.id %}">
                        {% csrf_token %}
                        <input type="hidden" value="confirmed" name="success">
                        <input type="submit" value="Подтвердить">
                    </form>
                    <form method="post" action="{% url 'success_statement' statement.id %}">
                        {% csrf_token %}
                        <input type="text" name="comment">
                        <input type="hidden" value="rejected" name="success">
                        <input type="submit" value="Отклонить">
                    </form>
                {% endif %}
            {% else %}
                <form method="get" action="{% url 'update_statement' statement.id %}">
                    <input type="submit" value="Update">
                </form>
                {% if statement.success == 'F' %}
                    <form method="post" action="{% url 'return_statement' statement.id %}">
                        {% csrf_token %}
                        <input type="submit" value="Return">
                    </form>
                {% endif %}
            {% endif %}
            <hr>
        {% endif %}

    {% endfor %}
{% endblock %}

templates/user_update_statement.html
{% extends 'base.html' %}


{% block title %}
    <title>Update Statement</title>
{% endblock %}


{% block content %}
    <span><a href="{% url 'logout' %}">Logout</a></span><br>
    <span><a href="{% url 'list' %}">List statement</a></span><br>
    <br><hr><br>

    <form method="post">
        {{ form.as_ul }}
        {% csrf_token %}
        <input type="submit" value="Update">
    </form>
{% endblock %}